# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dO45OiXAOBSH-IeihATAUrT_HVA8MFax
"""

x = int(input("Masukkan jumlah hari: "))

tahun = x // 365
sisa_hari = x % 365

bulan = sisa_hari // 30
hari = sisa_hari % 30

print("Hasil konversi:")
print("Tahun :", tahun)
print("Bulan :", bulan)
print("Hari  :", hari)

x = int(input("Masukkan angka: "))

for i in range(1, 101):
    if i % 3 == 0 and i % 5 == 0:
        print("fizzbuzz")
    elif i % 3 == 0:
        print("fizz")
    elif i % 5 == 0:
        print("buzz")
    else:
        print(i)